### ISSUE TITLE
install command needs to install  credentials for NNF fencing agent

### ISSUE THREAD

**Issue by NateThornton** [NearNodeFlash/nnf-deploy#47]
The fencing agent for NNF requires credentials for accessing the NNF Storage resource using the `nnf-controller-manager` secrets. This is an enhancement to ensure these credentials are installed along with other certificates using the `install` command.

**Comment by bdevcich-hpe** [comment]
@matthew-richerson could you outline the work that needs to be done for this?

**Comment by matthew-richerson** [comment]
I did this already. I didn't realize there was a GitHub issue for it.
